### ISSUE TITLE
Exception in demo code : A concurrent update was performed on this collection and corrupted its state.

### ISSUE THREAD

**Issue by anandsowm** [FuJianR/LiteDB.AzureBlob#3]
Ran the demo code after compiling it with target framework as .NET 7.0.
The Azure Block blob test case was executed.
The below is the exception raised and the stack trace : 

`
Unhandled exception. System.AggregateException: One or more errors occurred. (Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.)
 ---> System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at LiteDB.BsonDocument.set_Item(String key, BsonValue value)
   at LiteDB.BsonDocument.CopyTo(BsonDocument other)
   at LiteDB.Engine.IndexCost..ctor(CollectionIndex index, BsonExpression expr, BsonExpression value)
   at LiteDB.Engine.QueryOptimization.ChooseIndex(HashSet`1 fields)
   at LiteDB.Engine.QueryOptimization.DefineIndex()
   at LiteDB.Engine.QueryOptimization.ProcessQuery()
   at LiteDB.Engine.QueryExecutor.<>c__DisplayClass9_0.<<ExecuteQuery>g__RunQuery|0>d.MoveNext()
   at LiteDB.BsonDataReader..ctor(IEnumerable`1 values, String collection)
   at LiteDB.Engine.QueryExecutor.ExecuteQuery(Boolean executionPlan)
   at LiteDB.Engine.QueryExecutor.ExecuteQuery()
   at LiteDB.Engine.LiteEngine.Query(String collection, Query query)
   at LiteDB.LiteQueryable`1.ExecuteReader()
   at LiteDB.LiteQueryable`1.ToDocuments()+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at LiteDB.LiteCollection`1.FindById(BsonValue id)
   at Demo.Program.<>c__DisplayClass4_0.<TestReadDatabase>b__0(Int32 i)
`
If we knock off the use of `ParallelEnumerable`, and use only simple serial iteration, then as expected, this exception doesn't arise.

**Comment by ssteiner** [comment]
seems to work fine in my fork - I updated the PageBlob to use the latest Azure SDKs. I did note however, that there's plenty of concurrent download of blocks running the test - so I'm adding means to prevent that.
